import { pgTable, text, integer, bigint, uniqueIndex, primaryKey } from 'drizzle-orm/pg-core';
export const users = pgTable('users',{id:text('id').primaryKey(),email:text('email').notNull().unique(),password:text('password').notNull(),emailLoginEnabled:integer('email_login_enabled').notNull().default(1),emailVerified:integer('email_verified').notNull().default(1),name:text('name').notNull(),eaId:text('ea_id'),discordId:text('discord_id').unique(),avatarKey:text('avatar_key'),role:text('role').notNull().default('player'),createdAt:bigint('created_at',{mode:'number'}).notNull()});
export const adminInvites=pgTable('admin_invites',{email:text('email').primaryKey(),createdBy:text('created_by').notNull(),createdAt:bigint('created_at',{mode:'number'}).notNull()});
export const tournaments=pgTable('tournaments',{id:text('id').primaryKey(),name:text('name').notNull(),game:text('game').notNull(),format:text('format').notNull(),fee:integer('fee').notNull().default(0),capacity:integer('capacity').notNull(),rules:text('rules').notNull().default(''),prize:text('prize').notNull().default(''),mode:text('mode').notNull().default('X1'),startsAt:text('starts_at'),status:text('status').notNull().default('open'),ownerId:text('owner_id').notNull(),createdAt:bigint('created_at',{mode:'number'}).notNull()});
export const teams=pgTable('teams',{id:text('id').primaryKey(),tournamentId:text('tournament_id').notNull(),captainId:text('captain_id').notNull(),clubId:text('club_id'),groupId:text('group_id'),name:text('name').notNull(),platform:text('platform').notNull(),eaId:text('ea_id').notNull(),paymentStatus:text('payment_status').notNull().default('pending'),createdAt:bigint('created_at',{mode:'number'}).notNull()},t=>[uniqueIndex('team_captain_tournament').on(t.tournamentId,t.captainId)]);
export const tournamentGroups=pgTable('tournament_groups',{id:text('id').primaryKey(),tournamentId:text('tournament_id').notNull(),name:text('name').notNull(),ordinal:integer('ordinal').notNull()},t=>[uniqueIndex('tournament_group_ordinal').on(t.tournamentId,t.ordinal)]);
export const matches=pgTable('matches',{id:text('id').primaryKey(),tournamentId:text('tournament_id').notNull(),groupId:text('group_id'),homeId:text('home_id').notNull(),awayId:text('away_id').notNull(),homeGoals:integer('home_goals'),awayGoals:integer('away_goals'),homePenalties:integer('home_penalties'),awayPenalties:integer('away_penalties'),status:text('status').notNull().default('scheduled'),round:integer('round').notNull().default(1),createdAt:bigint('created_at',{mode:'number'}).notNull()});
export const bracketSlots=pgTable('bracket_slots',{id:text('id').primaryKey(),tournamentId:text('tournament_id').notNull(),round:integer('round').notNull(),slot:integer('slot').notNull(),homeId:text('home_id'),awayId:text('away_id'),winnerId:text('winner_id'),matchId:text('match_id')},t=>[uniqueIndex('bracket_slot_unique').on(t.tournamentId,t.round,t.slot),uniqueIndex('bracket_match_unique').on(t.matchId)]);
export const messages=pgTable('messages',{id:text('id').primaryKey(),matchId:text('match_id').notNull(),userId:text('user_id').notNull(),body:text('body').notNull(),createdAt:bigint('created_at',{mode:'number'}).notNull()});
export const submissions=pgTable('submissions',{id:text('id').primaryKey(),matchId:text('match_id').notNull(),userId:text('user_id').notNull(),homeGoals:integer('home_goals').notNull(),awayGoals:integer('away_goals').notNull(),homePenalties:integer('home_penalties'),awayPenalties:integer('away_penalties'),createdAt:bigint('created_at',{mode:'number'}).notNull()},t=>[uniqueIndex('submission_match_user').on(t.matchId,t.userId)]);
export const playerStats=pgTable('player_stats',{id:text('id').primaryKey(),matchId:text('match_id').notNull(),userId:text('user_id').notNull(),playerName:text('player_name').notNull().default(''),goals:integer('goals').notNull().default(0),assists:integer('assists').notNull().default(0),approved:integer('approved').notNull().default(0)});
export const sessions=pgTable('sessions',{id:text('id').primaryKey(),userId:text('user_id').notNull(),expiresAt:bigint('expires_at',{mode:'number'}).notNull()});
export const settings=pgTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});

export const clubs=pgTable('clubs',{id:text('id').primaryKey(),ownerId:text('owner_id').notNull(),name:text('name').notNull(),game:text('game').notNull(),mode:text('mode').notNull(),platform:text('platform').notNull(),eaId:text('ea_id').notNull(),description:text('description').notNull().default(''),roster:text('roster').notNull().default('[]'),crestKey:text('crest_key'),createdAt:bigint('created_at',{mode:'number'}).notNull()});
export const recruitment=pgTable('recruitment',{id:text('id').primaryKey(),clubId:text('club_id').notNull(),ownerId:text('owner_id').notNull(),position:text('position').notNull(),description:text('description').notNull(),createdAt:bigint('created_at',{mode:'number'}).notNull()});
export const recruitmentInterest=pgTable('recruitment_interest',{id:text('id').primaryKey(),postId:text('post_id').notNull(),userId:text('user_id').notNull(),message:text('message').notNull(),createdAt:bigint('created_at',{mode:'number'}).notNull()},t=>[uniqueIndex('interest_post_user').on(t.postId,t.userId)]);
export const adminPermissions=pgTable('admin_permissions',{userId:text('user_id').notNull(),permission:text('permission').notNull()},t=>[primaryKey({columns:[t.userId,t.permission]})]);
export const emailVerifications=pgTable('email_verifications',{email:text('email').primaryKey(),name:text('name').notNull(),password:text('password').notNull(),eaId:text('ea_id'),codeHash:text('code_hash').notNull(),attempts:integer('attempts').notNull().default(0),expiresAt:bigint('expires_at',{mode:'number'}).notNull(),createdAt:bigint('created_at',{mode:'number'}).notNull()});
